### ISSUE TITLE
Scaling issue : When 100+ PVCs are created at the same time, the CSI external-provisioner experiences timeout toward the plugin

### ISSUE THREAD

**Issue by tomerna** [kubernetes-csi/external-provisioner#211]
I noticed that when creating more than 100 PVCs at the same time, the CSI external-provisioner experiences timeout toward the plugin and eventually timeout the entire operation which ends up with pending pods without persistent volume attached.

{"log":"I0108 09:55:25.485371       1 controller.go:544] CreateVolumeRequest {Name:pvc-74c33958-132b-11e9-bdce-107d1a595b9b CapacityRange:required_bytes:1073741824000  VolumeCapabilities:[mount:\u003cfs_type:\"ext4\" \u003e access_mode:\u003cmode:SINGLE_NODE_WRITER \u003e ] Parameters:map[] Secrets:map[] VolumeContentSource:\u003cnil\u003e AccessibilityRequirements:\u003cnil\u003e XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}\n","stream":"stderr","time":"2019-01-08T09:55:25.48549066Z"}
{"log":"I0108 09:55:25.485464       1 controller.go:188] GRPC call: /csi.v1.Controller/CreateVolume\n","stream":"stderr","time":"2019-01-08T09:55:25.485508387Z"}
{"log":"I0108 09:55:25.485481       1 controller.go:189] GRPC request: {\"capacity_range\":{\"required_bytes\":1073741824000},\"name\":\"pvc-74c33958-132b-11e9-bdce-107d1a595b9b\",\"volume_capabilities\":[{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}}]}\n","stream":"stderr","time":"2019-01-08T09:55:25.48800868Z"}
{"log":"I0108 09:55:32.166606       1 controller.go:191] GRPC response: {}\n","stream":"stderr","time":"2019-01-08T09:55:32.167352526Z"}
{"log":"I0108 09:55:32.167294       1 controller.go:192] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2019-01-08T09:55:32.167376498Z"}
{"log":"W0108 09:55:32.167313       1 controller.go:592] **CreateVolume timeout: 10s has expired, operation** will be retried\n","stream":"stderr","time":"2019-01-08T09:55:32.167383366Z"}

**Comment by jsafrane** [comment]
With rebase to external-provisioner-lib 3.0 and recent changes in external-provisioner, the retry mechanism is different. Details will be documented in README that's being updated in https://github.com/kubernetes-csi/external-provisioner/pull/249

We now have exponential backoff with fast retries in the beginning, slowing down quickly and with no explicit number of attempts. Kubernetes API server and/or storage subsystem may be busy and return errors, but the controller should recover and provision everything at fast as API server and the storage is capable. There are some new cmdline arguments to tune things up for slower storage.

These PRs brought most of the fixes:

* https://github.com/kubernetes-csi/external-provisioner/pull/244
* https://github.com/kubernetes-csi/external-provisioner/pull/216

/close

**Comment by jsafrane** [comment]
To sum it up, I tested with 200 volumes on AWS.
* The old provisioner (1.0.1) was 2x slower with provisioning than the new one, mainly because now we have 100 workers instead of 4 (i.e. 100 AWS calls are done in parallel instead of 4). The new one could be even faster if it was not throttled by API server.

* Old provisioner is 2x **faster** than the new one, because API server does not like the rate of PV updates / deletes and throttles the provisioner heavily (it's still recovering from provisioning load).

The new provisioner is still a bit faster than the old one because provisioning is slower than deletion and its speedup is more thus significant, however, the major benefit is that its robustness has improved a lot and also it's more configurable to various storage backends.
