### ISSUE TITLE
Make fstype configurable while starting the external-provisioner

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-provisioner#328]
currently in external-provisioner fstype is set to `ext4` if nothing is passed in storage-class, we have a requirement to make it configurable so that the SP who is using the external-provisioner can choose the default fstype which they want to have it. This will avoid always mentioning of the fstype in the storage-class.

 in rbd csi plugin, we have seen better performance with `xfs` type, as external-provisioner is defaulting to `ext4`, in rbd csi we are asking users to mention the fstype as `xfs` in storage class. if fstype can be configured in external-provisioner user don't need to bother about the default fstype used.

CC @msau42

**Comment by Madhu-1** [comment]
@humblec FYI

**Comment by msau42** [comment]
I don't think fstype should be defaulted at all. There are filer types like nfs that expect a "" as the fstype

**Comment by humblec** [comment]
@msau42 As @Madhu-1 mentioned, fstype is set to `ext4`  in sidecar container if not passed in SC param  https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L437 , so the only way to get around this is via `SC` parameter which is actually on overhead as all SC has to set this field.

**Comment by msau42** [comment]
That doesn't seem right. Filer types like nfs/gluster/ceph should be failing when they validate fstype

**Comment by msau42** [comment]
See https://github.com/kubernetes/kubernetes/issues/65122

**Comment by humblec** [comment]
Have to go through in detail, but at glance , CSI pv source has been corrected. This has to be corrected here too. Isnt it ?

**Comment by msau42** [comment]
Yes I don't think external provisioner should default. Now the question is will we break drivers that expect a non empty value? Need to double check CSI spec wording in this

**Comment by humblec** [comment]
> Yes I don't think external provisioner should default. Now the question is will we break drivers that expect a non empty value? Need to double check CSI spec wording in this>

Yeah, we have to cross check on this, and also ( may be ) on backward compatibility of sidecar  ?

**Comment by msau42** [comment]
I spoke with @jsafrane and he suggested we add a `--default-fs` flag, which defaults to `ext4` and then immediately deprecate it. When we have a 2.0, we can remove the defaulting behavior.

Does this sound reasonable to you? Would you have time to work on this?

**Comment by jsafrane** [comment]
Well, we could have `--default-fs` flag, with `"ext4"` as default and then change the default to `""` after a long enough "deprecation" period - the flag would not be removed, just its default would change.

**Comment by msau42** [comment]
I prefer having the external provisioner not default anything at all and leave it entirely up to the plugin

**Comment by humblec** [comment]
> I spoke with @jsafrane and he suggested we add a `--default-fs` flag, which defaults to `ext4` and then immediately deprecate it. When we have a 2.0, we can remove the defaulting behavior.
> 
Sure. 

> Does this sound reasonable to you? Would you have time to work on this?

Sure. will work on this. thanks!

**Comment by msau42** [comment]
@humblec do you still have time to work on this?

**Comment by humblec** [comment]
> @humblec do you still have time to work on this?

@msau42 sure, let me put this in my todo list .

**Comment by SandeepPissay** [comment]
I agree with @msau42 that there should be no default FS type in external provisioner at all. The CSI driver can choose the default FS type based on various other factors like access mode and external provisioner should just pass fstype as empty string in create volume request.

**Comment by msau42** [comment]
Fixed in #400 
/close

**Comment by RaunakShah** [comment]
@msau42 @humblec I have a question about this bug. Basically what we're saying is that the storage provider should have the capability of choosing their own `fsType` (based on their own criteria) and Kubernetes will honor that. 

I have a bug where no `fsType` was provided (in the SC or provisioner) and our CSI driver defaulted to `ext4`. During `NodeStageVolume`, the volume is formatted - i can view the mount from the k8s node on which this pod was scheduled. 

However, Kubernetes' internal state assumes that `fsType` is empty (presumably because provisioner didn't set anything while making the `CreateVolume` request). The result is that the `securityContext` provided in the Pod spec is not honored. 

When i add the `--default-fsType` flag, this gets fixed. 

I've provided more details (logs, ref code) here - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/370#issuecomment-714710877

Is that the expected behavior? I'm thinking there should be some mechanism for the CSI driver to communicate back to Kubernetes what `fsType` (if any) was used to format the volume.

**Comment by msau42** [comment]
Good find. That is indeed a problem for plugins that need fsgroup support. For now, I think the best approach is to set the --default-fstype flag. In 1.20, we're targeting promoting the csidriver fsgroup feature to beta, which lets drivers explicitly opt in to supporting fsgroup instead of using this rwo + fstype heuristic.

**Comment by humblec** [comment]
Agree with both of you :) .. In short if SC and Provisioner does not specify `fsType` with this version of this sidecar, we have to set the `default-fstype` flag.

**Comment by RaunakShah** [comment]
Thanks for the info! I'll keep a look out for the fsgroup feature and make a change to our YAMLs for now

**Comment by bswartz** [comment]
None of the solutions work particularly well for meta-CSI plugins like Trident, which support multiple protocols and therefore multiple default FS types. The ideal solution from our perspective would be to allow the SP to tell the CO which fstype it defaulted to when the CO didn't specify one. That requires a CSI spec change though and I don't see it happening soon if ever.

The workaround we're going with is to tell our users to not leave the fstype blank in their storage classes.

**Comment by msau42** [comment]
Yes, I think we should look into adding something to CSI. Windows has a similar issue, in that you may want to default to a different filesystem depending on which node the pod gets scheduled to. @jingxu97 is looking into it

**Comment by SandeepPissay** [comment]
We have the same issue that vSphere CSI supports multiple protocols and we default to a protocol based on the create volume request. We definitely need to enhance CSI spec to communicate back the fstype that was used by CSI driver back to CO.
