### ISSUE TITLE
Build is not using vendor/ folder

### ISSUE THREAD

**Issue by davidz627** [kubernetes-csi/external-provisioner#394]
The default build using the `Makefile` and thus the `release-tools/build.make` file is not building with the vendor directory using `-mod=vendor` as a build flag. I assume since we're maintaining a vendor directory that this is something we want to do.

**Comment by msau42** [comment]
In travis and prow, it is setting -mod=vendor if it detects a vendor directory: https://github.com/kubernetes-csi/external-provisioner/search?q=GOFLAGS_VENDOR&unscoped_q=GOFLAGS_VENDOR

I'm not sure if there was any arguments for/against dev builds defaulting to build from vendor or not

**Comment by pohly** [comment]
The rationale for the current setup was that developers can decide for themselves whether they want to use the vendored sources. IMHO they benefit less from it because typically sources will get cached automatically on their development machine (which isn't the case in the CI) and it might be less convenient when changing dependencies. I think builds fail when adding a new dependency and then building with `-mod=vendor` without first putting the source into `vendor`.

**Comment by davidz627** [comment]
I don't think that CI build env should differ significantly from the dev build env if it can be avoided. This causes confusion.

**Comment by pohly** [comment]
> I don't think that CI build env should differ significantly from the dev build env if it can be avoided. 

Why do you think that the difference is significant? The only difference is *where* the files come from that "go build" uses; the *content* of the files is exactly the same and matches what is specified in `go.mod`.

> This causes confusion.

Can you elaborate further what kind of confusion will be caused by this?

I'm starting to get the impression that your concern is that developers will use different versions of the dependencies than the CI. But that can't happen because of the way how Go modules work: in contrast to before, the versions of the dependencies aren't specified by the code that is in the `vendor` dir but rather by `go.mod`, and that is used also without `-mod=vendor`.

**Comment by davidz627** [comment]
> The only difference is where the files come from that "go build" uses; the content of the files is exactly the same and matches what is specified in go.mod.

When files come from different places they are by definition different files. The content being "exactly the same" is based on synchronizing the two sources of truth. What happens when that assumption is broken in any way? When a module version is bumped but the corresponding vendor folder is not updated/synced? When local changes may be made to a vendor folder during the course of development?

In any case where the state of sync is not perfect the default dev environment and the CI environments will behave differently since one pulls pure dependences and another uses the vendor folder (which is the *one we care about*?).

Why would you want different source of truth for dev and CI if it can be avoided? What is the benefit to keeping dev not using the vendor folder? You said so yourself that by changing dev to using the vendor folder that:
> builds fail when adding a new dependency and then building with -mod=vendor without first putting the source into vendor.

which IMO *should* happen since the CI builds and the *real* image pushes will fail without that source in vendor. This is a perfect example of why making the dev environment use the same source of truth for modules as the CI is giving you a *real* signal that something needs to be fixed before you're in a good state. 


Additionally the argument that developers in local env:
> benefit less from it because typically sources will get cached automatically

doesn't track with me. They benefit less, but they still benefit. Caching automatically is something that will often happen but is also not guaranteed. Using the vendor folder seems to be an easy win here giving us benefits (but maybe less benefit than in CI).

**Comment by pohly** [comment]
David Zhu <notifications@github.com> writes:

>> The only difference is where the files come from that "go build" uses; the content of the files is exactly the same and matches what is specified in go.mod.
>
> When files come from different places they are by definition different
> files. The content being "exactly the same" is based on synchronizing
> the two sources of truth.

There's just one source of truth: the go.mod file.

We ensure that the vendor dir matches that with `make test-vendor`.

> What happens when that assumption is broken
> in any way? When a module version is bumped but the corresponding
> vendor folder is not updated/synced?

When we don't force the developer to use the vendor dir, everything
works as in other Go projects that don't do vendoring: `go build <some
package>` and `make build` both use `go.mod`.

If we always use the vendor dir in the Makefile, then developers may get
unexpected errors where a manual `go build` works and `make build` doesn't, unless developers always remember to do `go mod vendor` after changing dependencies.

> When local changes may be made to
> a vendor folder during the course of development?

The vendor dir can no longer be changed without first changing `go.mod`.

> Why would you want different source of truth for dev and CI if it can
> be avoided?

See above - there is only single source of truth.

> What is the benefit to keeping dev not using the vendor folder? You said so yourself that by changing dev to using the vendor folder that:
>> builds fail when adding a new dependency and then building with -mod=vendor without first putting the source into vendor.

That's the disadvantage of having `-mod=vendor` in the Makefile and the
reason why I prefer to *not* have it there.

Vendoring is something we kept for the CI. We even considered dropping it entirely but weren't sure how much slower the CI builds would become then because we didn't have any hard data on build speeds with and without it. So developer currently need to refresh it before submitting a PR, but other than that working on the code is done as envisioned when Go modules were designed. Vendoring was almost removed ("The initial series of vgo blog posts did propose dropping vendoring entirely", https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away) because it's not supposed to be needed anymore but some people (correctly) pointed out some usages for it.

If having a vendor dir causes confusion, then let's remove it.

**Comment by pohly** [comment]
It looks like fetching source is so fast that keeping the vendor directory is not justified. I just ran some builds of the external-provisioner (one of the more complex components) with and without vendor dir and the few data points that this gave show no obvious difference: https://github.com/kubernetes-csi/external-provisioner/pull/396

**Comment by pohly** [comment]
> > When local changes may be made to a vendor folder during the course of development?
>
> The vendor dir can no longer be changed without first changing go.mod.

... and for those cases where developers want to modify dependencies because they want to try out some change, the `replace` statement can be used temporarily to point to a locally modified copy of that dependencies. The Go mod FAQ describes that here: https://github.com/golang/go/wiki/Modules#can-i-work-entirely-outside-of-vcs-on-my-local-filesystem

**Comment by gnufied** [comment]
I have seen cases where a project completely disappears from github. I know that https://proxy.golang.org/ solves some of the pain with that, but I found vendored dependencies to be a godsend when this happens.

**Comment by pohly** [comment]
> I have seen cases where a project completely disappears from github.

Yes, that's one of the reasons why vendoring is useful. I also like that the source of dependencies is readily available for inspection, both while developing code and during PR reviews. We definitely need a wider discussion of the pros and cons before removing it.

In https://github.com/kubernetes-csi/external-provisioner/issues/394#issuecomment-573845998 I should have said "fetching source is so fast that keeping the vendor directory is not justified *for performance of the CI*".

> I know that https://proxy.golang.org/ solves some of the pain with that

Even that warns that "proxy.golang.org does not save all modules forever" (in the last answer).
