### ISSUE TITLE
Is it possible to run only one external-provisioner instance for all csi drivers?

### ISSUE THREAD

**Issue by wavezhang** [kubernetes-csi/external-provisioner#547]
I want to deploy multiple csi drivers to k8s, is it possible to run only one external-provisioner instance for all csi drivers?

**Comment by pohly** [comment]
This is not supported by the design of the external-provisioner. It always only talks to one CSI driver.

**Comment by wavezhang** [comment]
So， is this possible to redesign external-provisioner, and make it talks to multiple registered CSI drivers?

**Comment by wavezhang** [comment]
What is the main concern that  external-provisioner only talks to one CSI driver?

**Comment by pohly** [comment]
How would you let one instance of the external-provisioner connect to different CSI driver instances? Which communication would you use and how do you make it secure?

I suppose it's doable, but will get more complicated and then might not be worth it. The only advantage that I see in using one provisioner is to avoid overhead for the watches that each instance has. Do you see other advantages?

Besides the technical issue, who is then responsible for this external-provisioner instances? With the current model, the CSI driver developers provide instructions for *their* driver cluster admins follow those.

When using a single instance, the cluster admin needs a much better understanding of how to configure that instance and cannot rely on documentation by driver developers. Different drivers might even need different versions of the external-provisioner.

**Comment by wavezhang** [comment]
When CSI Spec is stable, is this possible to  make CSI drivers like CNI/CRI, storage developer only need to provider driver binary, and external-provisioner/attacher/snapshotter can run only one instance (or move to in tree ). ?

For the security issue, without the provisioner secret are stores in k8s secret, driver binary can do nothing to storage provider.

The advantages, I think is that k8s users/storage driver developers can care less, it will be more easy to developer drivers and use them.

The disadvantages is that now there are different versions of external-provisioner for various csi drivers, it 's hard to unify.

**Comment by pohly** [comment]
So this is about moving changing the API between Kubernetes and CSI drivers, in particular for provisioning and snapshotting. The current situation is that the external provisioning API is specific to Kubernetes and external-provisioner implements it for a CSI driver.

What you are proposing is to extend Kubernetes so that some component in it ("internal-provisioner") calls unmodified CSI drivers for provisioning. This is a significant change for Kubernetes. SIG-Storage already doesn't have enough people who contribute (my impression, might be wrong). I doubt that there is interest in taking on more work and future maintenance responsibility.
