### ISSUE TITLE
after updated CSIStorageCapacities the ResourceVersion is changed but not update into Controller.capacities

### ISSUE THREAD

**Issue by lrcstars** [kubernetes-csi/external-provisioner#554]
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L522

env:
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
external-provisioner: v2.1.0

Args:
  -v=5
  --csi-address=/csi/csi.sock
  --feature-gates=Topology=true
  --strict-topology=true
  --capacity-ownerref-level=0
  --enable-capacity=true
  --node-deployment=true
  --node-deployment-immediate-binding=false

Error:
E0203 10:13:14.221095       1 capacity.go:433] update CSIStorageCapacity for {segment:0xc000700c60 storageClassName:qwq-mysql-cluster-local-storage-data}: Operation cannot be fulfilled on csistoragecapacities.storage.k8s.io "csisc-tjcf7": the object has been modified; please apply your changes to the latest version and try again

I printed the log and found ResourceVersion  has been modified
so after update CSIStorageCapacities, dose new capacity need to be remember into cache?

**Comment by pohly** [comment]
The local cache is maintained by the informer. It will get updated eventually and then the normal retry mechanism after a failed update should cover this scenario. We have code elsewhere which updates the local cache after making changes, but I find that a bit questionable from a conceptual perspective: there's a small risk that updating the local copy will overwrite a more recent copy that has been received in the meantime.

Regarding the error: it shouldn't be something that needs attention. Should we perhaps add a dedicated error type check for this which reduces the log severity from "error" to an info message?

**Comment by lrcstars** [comment]
The problem is caused by concurrency
First(thread1): CSIStorageCapacities update
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L526

Second(thread2): func (c *Controller) onCAddOrUpdate Got the lock first and update new capacity to cache
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L590

Third(thread1):  got lock and update old capacity to cache
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L536

**Comment by lrcstars** [comment]
So, Now that `The local cache is maintained by the informer`, then it's better to delete this code
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L536

**Comment by lrcstars** [comment]
The problem isn't that simple. Have another bug:
If capacity keeps changing. external-provisioner will keeps updateing  CSIStorageCapacities:
log:
I0204 14:58:44.791588       1 capacity.go:525] Capacity Controller: updating csisc-wwv65 for {segment:0xc000780e40 storageClassName:hello-world-storage-class}, new capacity 11598736Ki
I0204 14:58:44.794607       1 capacity.go:570] Capacity Controller: CSIStorageCapacity csisc-wwv65 is already known to match {segment:0xc000780e40 storageClassName:hello-world-storage-class}
I0204 14:58:44.794640       1 capacity.go:574] Capacity Controller: CSIStorageCapacity csisc-wwv65 was modified by someone, enqueueing {0xc000780e40 hello-world-storage-class} for fixing

**Comment by pohly** [comment]
> The local cache is maintained by the informer.

Scratch that. I was thinking of the informer cache here. The more complex `capacities` map is maintained by the controller: https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L88-L91

We can't use an informer cache with indexer either because `capacities` is supposed to contain all desired object, including the ones that haven't been created yet. The informer cache represents what exists in the apiserver.

What if we move up the locking from here:
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L532-L541
to before the code which potentially sends the new or updated object to the apiserver?
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L498

That limits parallelism because we hold the lock while executing a (potentially) longer running operation, but it should avoid the race.

An implementation of that approach is in https://github.com/kubernetes-csi/external-provisioner/pull/558

**Comment by lrcstars** [comment]
I think delete these code can fix
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L532-L541
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L582-L587

**Comment by pohly** [comment]
> I think delete these code can fix

But isn't that then leading to the scenario from https://github.com/kubernetes-csi/external-provisioner/issues/554#issuecomment-773084757 or was that without that change?

> Is this being overly cautious?

It was meant to protect against admin mistakes. It's not strictly necessary, but as long as the bookkeeping in `capacities` is done correctly, it should never trigger in normal operations.

**Comment by pohly** [comment]
After describing it like that, perhaps it should become a warning.

**Comment by lrcstars** [comment]
Your PR can solve both of the problems I've described, but as you say 
`That limits parallelism because we hold the lock while executing a (potentially) longer running operation, but it should avoid the race.`
My idea is to remove an update for `capacities`, so delete this:
https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L532-L541
after delete the code above, 会产生问题：https://github.com/kubernetes-csi/external-provisioner/issues/554#issuecomment-773084757, so delete this:https://github.com/kubernetes-csi/external-provisioner/blob/b7a8fe9fe487b11383e922170f4d34ee11ded78f/pkg/capacity/capacity.go#L582-L587

**Comment by pohly** [comment]
So you are proposing that we trust admins a bit more. That's probably fine: normal users can't create or update these objects and admins should know better than to mess with automatically created objects. Even if they do by mistake, the periodic refresh will fix it eventually.

So I'm fine with merging #559. I'll comment there for some further cleanup (basically just commit hygiene).

BTW, are you running this at a larger scale? That it'll break clusters when many of these objects have to be created and updated is the main objection against the approach. It would be good to get some real-world feedback and information about the kind of workload that it is used with.

**Comment by pohly** [comment]
I started updating PR #559  by adding more comments about how handling of the `capacities` map should work. I wrote:
```
	// capacities contains one entry for each object that is supposed
	// to exist. Entries that exist on the API server have a non-nil
	// pointer. Those get added exclusively through the informer
	// event handler to avoid races.
	capacities     map[workItem]*storagev1alpha1.CSIStorageCapacity
```

Then it occurred to me that there was another path where before the PR `capacities` was updated locally: after a `Create`. That is important to avoid creating two different objects for the same topology/storage class.

However, this should be fine, too. If it happens that we end up creating two objects, eventually both will be received by the event handler. The first one will be stored. The second will be recognized as a duplicated and then get deleted again. Because the two objects must have been created very close together, they probably had the same capacity, so scheduling isn't affected.

@lrcstars makes sense?

**Comment by lrcstars** [comment]
It makes sense.
I did overlook `creating two different objects for the same topology/storage class`
Thanks!

**Comment by pohly** [comment]
The change also broke the unit test for correcting capacity information after an update by an admin. We changed the behavior, so that test became obsolete.

@lrcstars I created https://github.com/kubernetes-csi/external-provisioner/pull/565 with your change and added some of my own. Can you review that?

**Comment by lrcstars** [comment]
revised.
The commentary makes it very clear.
I didn't read the part about the test. I'm not familiar with it.
