### ISSUE TITLE
Do not log secret in log

### ISSUE THREAD

**Issue by karataliu** [kubernetes-csi/external-provisioner#82]
https://github.com/kubernetes-csi/external-provisioner/blob/v0.2.1/pkg/controller/controller.go#L89

This line will log 'controller_create_secrets' if present

**Comment by shubheksha** [comment]
I'll work on this!

**Comment by pohly** [comment]
Instead of changing the logging, we could also just warn about this pitfall. It is limited to loglevel >= 5 (i.e. not the default).

Note that the CSI example .yaml *does* use such a high log level, though. So there is definitely a risk that people accidentally log secrets.

I'm undecided myself. Thoughts anyone?

**Comment by jsafrane** [comment]
I got an idea, perhaps we can add a new argument `--log-csi-messages` with clear description in --help output that it logs also secrets.
